### ISSUE TITLE
curl 7.64, 7.70 armeabi-v7a on android 4.2.2 getting error "CANNOT LINK EXECUTABLE"

### ISSUE THREAD

**Issue by Baltazar500** [robertying/openssl-curl-android#3]
On android 4.2.2, the launch of the curl binary version 7.64 and 7.70 ends with a crash

strace log : [strace.txt](https://github.com/robertying/openssl-curl-android/files/5221745/strace.txt)

**Comment by Baltazar500** [comment]
Zackptg5 helped solve this problem. For android 4.2.2, when building, you need to use the minimum api 17 :)

**Comment by robertying** [comment]
Nice! I didn't have time to investigate this issue. Glad you solved it!

**Comment by Baltazar500** [comment]
>Nice! I didn't have time to investigate this issue. Glad you solved it!

ОК. Will you build new releases with a minimum api of 17 ?

**Comment by robertying** [comment]
The build process is pretty much well described in the README. You could build it to suit your own need.

I can't possibly build for all API versions, so the point of this repo is to show how to build one of your own.
