### ISSUE TITLE
I got link error while I am linking the libcurl.a into myproject

### ISSUE THREAD

**Issue by stevenetease** [robertying/openssl-curl-android#5]
I also link the libcrypto.a and libssl.a before the libcurl.a,but still cant find those sumbols.

36>ld.lld: error: undefined symbol: __FD_SET_chk
36>>>> referenced by multi.c
36>>>>               libcurl_la-multi.o:(curl_multi_fdset) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>>>> referenced by multi.c
36>>>>               libcurl_la-multi.o:(curl_multi_fdset) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_finish
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_close_all) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_set_engine) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_free
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_close_all) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_set_engine) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_set_engine) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_by_id
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_set_engine) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_init
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_set_engine) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_set_default
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_set_engine_default) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_get_id
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_set_engine_default) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_engines_list) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_get_first
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_engines_list) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_get_next
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_engines_list) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_ctrl
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_connect_common) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: ENGINE_ctrl_cmd
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_connect_common) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>ld.lld: error: undefined symbol: UI_OpenSSL
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_connect_common) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ossl_connect_common) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>>>> referenced by openssl.c
36>>>>               libcurl_la-openssl.o:(ssl_ui_reader) in archive D:\myproject\libs\curl/lib_android/armeabi-v7a/libcurl.a
36>>>> referenced by openssl.c

**Comment by robertying** [comment]
I built and ran my [demo project](https://github.com/robertying/AndroidCurlExample) with the latest release and it turned out working.

Can you look into this [demo](https://github.com/robertying/AndroidCurlExample) and see if it helps solve your problem?

**Comment by stevenetease** [comment]
噢，这是因为我链接了另外一个libssl.a导致的问题。
